### ISSUE TITLE
 capacitron_use_speaker_embedding not used in the code

### ISSUE THREAD

**Issue by a-froghyar** [a-froghyar/Capacitron#2]

**Comment by a-froghyar** [comment]
During testing: 

```
!! Error creating Test Sentence - 3
Traceback (most recent call last):
  File "./TTS/bin/train_tacotron.py", line 461, in evaluate
    wav, alignment, decoder_output, postnet_output, stop_tokens, _ = synthesis(
  File "/home/julian/workspace/Capacitron/TTS/tts/utils/synthesis.py", line 265, in synthesis
    decoder_output, postnet_output, alignments, stop_tokens = run_model_torch(
  File "/home/julian/workspace/Capacitron/TTS/tts/utils/synthesis.py", line 67, in run_model_torch
    decoder_output, postnet_output, alignments, stop_tokens = model.inference(
  File "/home/julian/miniconda3/envs/TTS/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/home/julian/workspace/Capacitron/TTS/tts/models/tacotron.py", line 207, in inference
    encoder_outputs = self._concat_speaker_embedding(encoder_outputs, speaker_embeddings)
  File "/home/julian/workspace/Capacitron/TTS/tts/models/tacotron_abstract.py", line 222, in _concat_speaker_embedding
    speaker_embeddings_ = speaker_embeddings.expand(
RuntimeError: The expanded size of the tensor (70) must match the existing size (256) at non-singleton dimension 1.  Target sizes: [1, 70, -1].  Tensor sizes: [256, 1]
```

**Comment by a-froghyar** [comment]
Closing because the training wasn't initiated on the `dev-capacitron-dev` branch
