### ISSUE TITLE
LR Scheduler Bug when continuing training

### ISSUE THREAD

**Issue by a-froghyar** [a-froghyar/Capacitron#4]
```
Traceback (most recent call last):
  File "./TTS/bin/train_tacotron.py", line 909, in <module>
    main(args)
  File "./TTS/bin/train_tacotron.py", line 830, in main
    scheduler = StepwiseGradualLR(optimizer,
  File "/home/julian/workspace/Capacitron/TTS/utils/training.py", line 108, in __init__
    super(StepwiseGradualLR, self).__init__(optimizer, last_epoch)
  File "/home/julian/miniconda3/envs/TTS/lib/python3.8/site-packages/torch/optim/lr_scheduler.py", line 39, in __init__
    raise KeyError("param 'initial_lr' is not specified "
KeyError: "param 'initial_lr' is not specified in param_groups[0] when resuming an optimizer"
```

**Comment by a-froghyar** [comment]
We're getting rid of the scheduler so closing this
